Rearranged startGroovy so that it works on Ubuntu as well as Solaris, Mac OS X, Windows+Cygwin.
git-svn-id: http://svn.codehaus.org/groovy/trunk/groovy/groovy-core@4241 a5544e8c-8a19-0410-ba12-f9af4593a198

diff --git a/src/bin/startGroovy b/src/bin/startGroovy
--- a/src/bin/startGroovy
+++ b/src/bin/startGroovy
@@ -1,3 +1,5 @@
+# -*- mode:sh -*-
+
 ##############################################################################
 ##                                                                          ##
 ##  Groovy JVM Bootstrap for UN*X                                           ##
@@ -5,129 +7,129 @@
 ##############################################################################
 
 ##
-## $Revision$ $Date$
+## $Revision$
+## $Date$
 ##
 
 PROGNAME=`basename "$0"`
-DIRNAME=`dirname "$0"`
 
-# Use the maximum available, or set MAX_FD != -1 to use that
+#DIRNAME=`dirname "$0"`
+
+# Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD="maximum"
 
-warn() {
+warn ( ) {
     echo "${PROGNAME}: $*"
 }
 
-die() {
+die ( ) {
     warn "$*"
     exit 1
 }
 
-earlyInit() {
-	return
-}
-lateInit() {
-	return
+earlyInit ( ) {
+    return
 }
 
-GROOVY_STARTUP=~/.groovy/startup
-if [ -r "$GROOVY_STARTUP" ]; then
-	. "$GROOVY_STARTUP"
+lateInit ( ) {
+    return
+}
+
+GROOVY_STARTUP="$HOME/.groovy/startup"
+if [ -r "$GROOVY_STARTUP" ] ; then
+    . "$GROOVY_STARTUP"
 fi
 
 earlyInit
 
 # OS specific support (must be 'true' or 'false').
-cygwin=false;
-darwin=false;
+cygwin=false
+msys=false
+darwin=false
 case "`uname`" in
-    CYGWIN*)
-        cygwin=true
-        ;;
-        
-    Darwin*)
-        darwin=true
-        ;;
+  CYGWIN* )
+    cygwin=true
+    ;; 
+  Darwin* )
+    darwin=true
+    ;;
+  MINGW* )
+    msys=true
+    ;;
 esac
 
-if [ "$1" = "-cp" ] || [ "$1" = "-classpath" ]; then
-  CP=$2
-  shift 2
+if [ "$1" = "-cp" -o "$1" = "-classpath" ] ; then
+    CP=$2
+    shift 2
 fi
 
-# Attempt to set JAVA_HOME if it's not already set
-if [ -z "$JAVA_HOME" ]; then
-	
-	# Set JAVA_HOME for Darwin
-	if $darwin; then
-		
-		[ -z "$JAVA_HOME" -a -d "/Library/Java/Home" ] &&
-			export JAVA_HOME="/Library/Java/Home"
-			
-		[ -z "$JAVA_HOME" -a -d "/System/Library/Frameworks/JavaVM.framework/Home" ] &&
-			export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
-		
-	fi
-	
-fi
-
-# For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-    [ -n "$GROOVY_HOME" ] &&
-        GROOVY_HOME=`cygpath --unix "$GROOVY_HOME"`
-    [ -n "$JAVACMD" ] &&
-        JAVACMD=`cygpath --unix "$JAVACMD"`
-    [ -n "$JAVA_HOME" ] &&
-        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-    [ -n "$CP" ] &&
-        CP=`cygpath --path --unix "$CP"`
-fi
-
-# Locate GROOVY_HOME if not it is not set
-if [ -z "$GROOVY_HOME" -o ! -d "$GROOVY_HOME" ] ; then
-  # resolve links - $0 may be a link to groovy's home
-  PRG="$0"
-
-  # need this for relative symlinks
-  while [ -h "$PRG" ] ; do
-    ls=`ls -ld "$PRG"`
-    link=`expr "$ls" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
-    PRG="$link"
+# Attempt to set JAVA_HOME if it's not already set.
+if [ -z "$JAVA_HOME" ] ; then
+    if $darwin ; then 
+        [ -z "$JAVA_HOME" -a -d "/Library/Java/Home" ] && export JAVA_HOME="/Library/Java/Home"
+        [ -z "$JAVA_HOME" -a -d "/System/Library/Frameworks/JavaVM.framework/Home" ] && export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
     else
-    PRG=`dirname "$PRG"`"/$link"
+        javaExecutable="`which javac`"
+        [ -z "$javaExecutable" -o "`expr \"$javaExecutable\" : '\([^ ]*\)'`" = "no" ] && die "JAVA_HOME not set and cannot find javac to deduce location, please set JAVA_HOME."
+        # readlink(1) is not available as standard on Solaris 10.
+        readLink=`which readlink`
+        [ `expr "$readLink" : '\([^ ]*\)'` = "no" ] && die "JAVA_HOME not set and readlink not available, please set JAVA_HOME."
+        javaExecutable="`readlink -f \"$javaExecutable\"`"
+        javaHome="`dirname \"$javaExecutable\"`"
+        javaHome=`expr "$javaHome" : '\(.*\)/bin'`
+        export JAVA_HOME="$javaHome"
     fi
-  done
-
-  SAVED="`pwd`"
-  cd "`dirname \"$PRG\"`/.."
-  GROOVY_HOME="`pwd -P`"
-  cd "$SAVED"
 fi
 
-# Use default groovy-conf config
-if [ -z "$GROOVY_CONF" ]; then
+# For Cygwin, ensure paths are in UNIX format before anything is touched.
+if $cygwin ; then
+    [ -n "$GROOVY_HOME" ] && GROOVY_HOME=`cygpath --unix "$GROOVY_HOME"`
+    [ -n "$JAVACMD" ] && JAVACMD=`cygpath --unix "$JAVACMD"`
+    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+    [ -n "$CP" ] && CP=`cygpath --path --unix "$CP"`
+fi
+
+# Attempt to set GROOVY_HOME if it is not already set.
+if [ -z "$GROOVY_HOME" -o ! -d "$GROOVY_HOME" ] ; then
+    # Resolve links: $0 may be a link to groovy's home.
+    PRG="$0"
+    # Need this for relative symlinks.
+    while [ -h "$PRG" ] ; do
+        ls=`ls -ld "$PRG"`
+        link=`expr "$ls" : '.*-> \(.*\)$'`
+        if expr "$link" : '/.*' > /dev/null; then
+            PRG="$link"
+        else
+            PRG=`dirname "$PRG"`"/$link"
+        fi
+    done
+    SAVED="`pwd`"
+    cd "`dirname \"$PRG\"`/.."
+    GROOVY_HOME="`pwd -P`"
+    cd "$SAVED"
+fi
+
+# Set the default Groovy config if no specific one is mentioned.
+if [ -z "$GROOVY_CONF" ] ; then
     GROOVY_CONF="$GROOVY_HOME/conf/groovy-starter.conf"
 fi
 STARTER_CLASSPATH="$GROOVY_HOME/lib/groovy-starter.jar"
 
-# Create the final classpath
-# Setting a classpath using the -cp or -classpath option means not to use
-# the global classpath. Groovy behaves then the same as the java 
-# interpreter
-if [ -n "$CP" ]; then
-  CP=$CP:$STARTER_CLASSPATH:.
-  if [ -n "$CLASSPATH" ]; then
-    STARTER_CLASSPATH=$STARTER_CLASSPATH:$CLASSPATH
-  fi
+# Create the final classpath. Setting a classpath using the -cp or -classpath option means not to use the
+# global classpath. Groovy behaves then the same as the java interpreter
+if [ -n "$CP" ] ; then
+    CP="$CP":"$STARTER_CLASSPATH":.
+    if [ -n "$CLASSPATH" ] ; then
+        STARTER_CLASSPATH="$STARTER_CLASSPATH":"$CLASSPATH"
+    fi
 else
-  CP=$STARTER_CLASSPATH:.
+    CP="$STARTER_CLASSPATH":.
 fi
 
-# Determine the Java command to use to start the JVM
-if [ -z "$JAVACMD" ]; then
-    if [ -n "$JAVA_HOME" ]; then
-        if [ -x "$JAVA_HOME/jre/sh/java" ]; then
+# Determine the Java command to use to start the JVM.
+if [ -z "$JAVACMD" ] ; then
+    if [ -n "$JAVA_HOME" ] ; then
+        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
             # IBM's JDK on AIX uses strange locations for the executables
             JAVACMD="$JAVA_HOME/jre/sh/java"
         else
@@ -137,24 +139,22 @@ if [ -z "$JAVACMD" ]; then
         JAVACMD="java"
     fi
 fi
-if [ ! -x "$JAVACMD" ]; then
-    die "JAVA_HOME is not defined correctly; can not execute: $JAVACMD"
+if [ ! -x "$JAVACMD" ] ; then
+    die "JAVA_HOME is not defined correctly, can not execute: $JAVACMD"
 fi
 if [ -z "$JAVA_HOME" ] ; then
     warn "JAVA_HOME environment variable is not set"
 fi
 
-# Increase the maximum file descriptors if we can
-if [ "$cygwin" = "false" ]; then
+# Increase the maximum file descriptors if we can.
+if [ "$cygwin" = "false" ] ; then
     MAX_FD_LIMIT=`ulimit -H -n`
-    if [ $? -eq 0 ]; then
-        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-            # use the businessSystem max
+    if [ $? -eq 0 ] ; then
+        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
             MAX_FD="$MAX_FD_LIMIT"
         fi
-        
         ulimit -n $MAX_FD
-        if [ $? -ne 0 ]; then
+        if [ $? -ne 0 ] ; then
             warn "Could not set maximum file descriptor limit: $MAX_FD"
         fi
     else
@@ -164,8 +164,8 @@ fi
 
 # Setup Profiler
 useprofiler=false
-if [ "x$PROFILER" != "x" ]; then
-    if [ -r "$PROFILER" ]; then
+if [ "$PROFILER" != "" ] ; then
+    if [ -r "$PROFILER" ] ; then
         . $PROFILER
         useprofiler=true
     else
@@ -180,75 +180,67 @@ TOOLS_JAR="$JAVA_HOME/lib/tools.jar"
 #fi
 
 # For Cygwin, switch paths to Windows format before running java
-if $cygwin; then
+if $cygwin ; then
     GROOVY_HOME=`cygpath --path --mixed "$GROOVY_HOME"`
     JAVA_HOME=`cygpath --path --mixed "$JAVA_HOME"`
     GROOVY_CONF=`cygpath --path --mixed "$GROOVY_CONF"`
     CP=`cygpath --path --mixed "$CP"`    
     TOOLS_JAR=`cygpath --path --mixed "$TOOLS_JAR"`
     STARTER_CLASSPATH=`cygpath --path --mixed "$STARTER_CLASSPATH"`
-	# We build the pattern for arguments to be converted via cygpath
+
+    # We build the pattern for arguments to be converted via cygpath
     ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
     SEP=""
-    for dir in $ROOTDIRSRAW; do
-    	ROOTDIRS="$ROOTDIRS$SEP$dir"
-	    SEP="|"
+    for dir in $ROOTDIRSRAW ; do
+        ROOTDIRS="$ROOTDIRS$SEP$dir"
+        SEP="|"
     done
     OURCYGPATTERN="(^($ROOTDIRS))"
     # Add a user-defined pattern to the cygpath arguments
     if [ "$GROOVY_CYGPATTERN" != "" ] ; then
-    	OURCYGPATTERN="$OURCYGPATTERN|($GROOVY_CYGPATTERN)"
+        OURCYGPATTERN="$OURCYGPATTERN|($GROOVY_CYGPATTERN)"
     fi
     # Now convert the arguments
     declare -i count
     for arg in "$@" ; do
-    	CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
-    	if [ $CHECK -ne 0 ] ; then
-	    	convArg=`cygpath --path --ignore --mixed "$arg"`
-    	else
-			convArg=$arg
-    	fi
-    	ARGUMENTS[$count]=$convArg
-    	count+=1
+        CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
+        if [ $CHECK -ne 0 ] ; then
+            convArg=`cygpath --path --ignore --mixed "$arg"`
+        else
+            convArg=$arg
+        fi
+        ARGUMENTS[$count]=$convArg
+        count+=1
     done
+
+    #  For some bizarre reason Dash (/bin/sh) on Ubuntu 6.10 Edgy Eft will not parse the array expression
+    #  needed for the Cygwin version of the exec command.  The only solution is for Dash not to see the text
+    #  at all :-(
+
+    . "$DIRNAME/startGroovy_cygwin"
+else
+    startGroovy ( ) {
+        CLASS=$1
+        shift
+    # Start the Profiler or the JVM
+        if $useprofiler ; then
+            runProfiler
+        else
+            exec "$JAVACMD" $JAVA_OPTS \
+                -classpath "$STARTER_CLASSPATH" \
+                -Dprogram.name="$PROGNAME" \
+                -Dgroovy.starter.conf="$GROOVY_CONF" \
+                -Dgroovy.home="$GROOVY_HOME" \
+                -Dtools.jar="$TOOLS_JAR" \
+                $STARTER_MAIN_CLASS \
+                --main $CLASS \
+                --conf "$GROOVY_CONF" \
+                --classpath "$CP" \
+                "$@"
+        fi
+    }    
 fi
 
 STARTER_MAIN_CLASS=org.codehaus.groovy.tools.GroovyStarter
 
 lateInit
-
-startGroovy() {
-  CLASS=$1
-  shift
-  
-  # Start the Profiler or the JVM
-  if $useprofiler; then
-      runProfiler
-  else
-  	if $cygwin; then
-         exec "$JAVACMD" $JAVA_OPTS \
-          -classpath "$STARTER_CLASSPATH" \
-          -Dprogram.name="$PROGNAME" \
-          -Dgroovy.starter.conf="$GROOVY_CONF" \
-          -Dgroovy.home="$GROOVY_HOME" \
-          -Dtools.jar="$TOOLS_JAR" \
-          $STARTER_MAIN_CLASS \
-          --main $CLASS \
-          --conf "$GROOVY_CONF" \
-          --classpath "$CP" \
-          "${ARGUMENTS[@]}"
-  	else
-         exec "$JAVACMD" $JAVA_OPTS \
-          -classpath "$STARTER_CLASSPATH" \
-          -Dprogram.name="$PROGNAME" \
-          -Dgroovy.starter.conf="$GROOVY_CONF" \
-          -Dgroovy.home="$GROOVY_HOME" \
-          -Dtools.jar="$TOOLS_JAR" \
-          $STARTER_MAIN_CLASS \
-          --main $CLASS \
-          --conf "$GROOVY_CONF" \
-          --classpath "$CP" \
-          "$@"
-  	fi
-  fi
-}
