Ignore failure for removing large unused packages

diff --git a/.github/workflows/groovy-build-dist.yml b/.github/workflows/groovy-build-dist.yml
--- a/.github/workflows/groovy-build-dist.yml
+++ b/.github/workflows/groovy-build-dist.yml
@@ -35,17 +35,21 @@ jobs:
         run: sudo apt-get install -y graphviz
       - name: Free disk space
         run: |
-          echo "Removing large unused packages"
-          sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable powershell mono-devel >/dev/null 2>&1
-          sudo apt-get autoclean -y >/dev/null 2>&1
-          sudo apt-get clean -y >/dev/null 2>&1
-          sudo apt-get autoremove -y >/dev/null 2>&1
+          {
+            echo "Removing large unused packages"
+            sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable powershell mono-devel >/dev/null 2>&1
+            sudo apt-get autoclean -y >/dev/null 2>&1
+            sudo apt-get clean -y >/dev/null 2>&1
+            sudo apt-get autoremove -y >/dev/null 2>&1
 
-          echo "Removing large unused files/directories"
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/lib/node_modules /usr/local/share/powershell /usr/local/share/chromium
-          sudo rm -rf /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" /usr/local/graalvm /usr/local/.ghcup
+            echo "Removing large unused files/directories"
+            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/lib/node_modules /usr/local/share/powershell /usr/local/share/chromium
+            sudo rm -rf /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" /usr/local/graalvm /usr/local/.ghcup
 
-          sudo df -h
+            sudo df -h
+          } || {
+            echo "[WARNING] Failed to remove large unused packages"
+          }
       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
